#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-formattable
Version  : 0.2.1
Release  : 19
URL      : https://cran.r-project.org/src/contrib/formattable_0.2.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/formattable_0.2.1.tar.gz
Summary  : Create 'Formattable' Data Structures
Group    : Development/Tools
License  : MIT
Requires: R-htmltools
Requires: R-htmlwidgets
Requires: R-knitr
Requires: R-rmarkdown
BuildRequires : R-DT
BuildRequires : R-htmltools
BuildRequires : R-htmlwidgets
BuildRequires : R-knitr
BuildRequires : R-rmarkdown
BuildRequires : buildreq-R

%description
'Formattable' vectors are printed with text formatting, and formattable
    data frames are printed with multiple types of formatting in HTML
    to improve the readability of data presented in tabular form rendered in
    web pages.

%prep
%setup -q -c -n formattable
cd %{_builddir}/formattable

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641020127

%install
export SOURCE_DATE_EPOCH=1641020127
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library formattable
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library formattable
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library formattable
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc formattable || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/formattable/DESCRIPTION
/usr/lib64/R/library/formattable/INDEX
/usr/lib64/R/library/formattable/LICENSE
/usr/lib64/R/library/formattable/Meta/Rd.rds
/usr/lib64/R/library/formattable/Meta/features.rds
/usr/lib64/R/library/formattable/Meta/hsearch.rds
/usr/lib64/R/library/formattable/Meta/links.rds
/usr/lib64/R/library/formattable/Meta/nsInfo.rds
/usr/lib64/R/library/formattable/Meta/package.rds
/usr/lib64/R/library/formattable/Meta/vignette.rds
/usr/lib64/R/library/formattable/NAMESPACE
/usr/lib64/R/library/formattable/NEWS
/usr/lib64/R/library/formattable/R/formattable
/usr/lib64/R/library/formattable/R/formattable.rdb
/usr/lib64/R/library/formattable/R/formattable.rdx
/usr/lib64/R/library/formattable/doc/formattable-data-frame.R
/usr/lib64/R/library/formattable/doc/formattable-data-frame.Rmd
/usr/lib64/R/library/formattable/doc/formattable-data-frame.html
/usr/lib64/R/library/formattable/doc/index.html
/usr/lib64/R/library/formattable/doc/introduction.R
/usr/lib64/R/library/formattable/doc/introduction.Rmd
/usr/lib64/R/library/formattable/doc/introduction.html
/usr/lib64/R/library/formattable/help/AnIndex
/usr/lib64/R/library/formattable/help/aliases.rds
/usr/lib64/R/library/formattable/help/formattable.rdb
/usr/lib64/R/library/formattable/help/formattable.rdx
/usr/lib64/R/library/formattable/help/paths.rds
/usr/lib64/R/library/formattable/html/00Index.html
/usr/lib64/R/library/formattable/html/R.css
/usr/lib64/R/library/formattable/htmlwidgets/formattable_widget.js
/usr/lib64/R/library/formattable/htmlwidgets/formattable_widget.yaml
/usr/lib64/R/library/formattable/tests/testthat.R
/usr/lib64/R/library/formattable/tests/testthat/test-formats.R
/usr/lib64/R/library/formattable/tests/testthat/test-formattable.R
/usr/lib64/R/library/formattable/tests/testthat/test-formatter.R
/usr/lib64/R/library/formattable/tests/testthat/test-render.R
/usr/lib64/R/library/formattable/tests/testthat/test-style.R
/usr/lib64/R/library/formattable/tests/testthat/test-transform.R
/usr/lib64/R/library/formattable/tests/testthat/test-utils.R
